backend:
  name: git-gateway
  branch: main

media_folder: public/products/images
public_folder: /products/images

collections:
  - name: rings
    label: Rings
    folder: public/products/rings
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Price
        name: price
        widget: number
      - label: Material
        name: material
        widget: string
      - label: Images
        name: images
        widget: image
        multiple: true
