backend:
  name: github
  repo: bhavesh65321/KP_jewellers
  branch: main

media_folder: public/products/images
public_folder: /products/images

collections:
  - name: rings
    label: Rings
    folder: public/products/rings
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
