backend:
  name: github
  repo: bhavesh65321/KP_jewellers
  branch: main

media_folder: "public/products/images"
public_folder: "/products/images"

collections:
  - name: "rings"
    label: "Rings"
    folder: "public/products/rings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Material", name: "material", widget: "string" }
      - { label: "Weight", name: "weight", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Images", name: "images", widget: "image", multiple: true }
